// 利用者に表示する固定文言。キーは文言を変えても維持する。
export const ja = {
  "common.cancel": "キャンセル",
  "common.edit": "編集",
  "common.delete": "削除",
  "common.back": "戻る",
  "common.close": "閉じる",
  "common.open": "開く",
  "common.reuse": "再利用",
  "common.draft": "下書き",
  "common.unset": "未設定",
  "common.unassigned": "未指定",
  "common.assignee": "担当者",
  "common.state": "状態",
  "common.processing": "処理しています…",
  "common.select": "選んでください",
  "common.clearSelection": "選択を解除",
  "common.moveUp": "上へ",
  "common.moveDown": "下へ",
  "portal.structure": "アプリの構造",
  "portal.audience": "家族や仲間との情報を整理します",
  "portal.title": "情報共有の入口",
  "portal.tagline": "日々の記録をアプリにまとめられます。",
  "portal.description": "家族の予定や仲間とのメモをアプリで整理できます。",
  "portal.create": "アプリを作る",
  "portal.apps": "アプリ",
  "portal.emptyTitle": "アプリはまだありません",
  "portal.emptyDescription":
    "必要な項目を選んでアプリを作れます。テンプレートも使えます。",
  "portal.fromTemplate": "テンプレートから作る",
  "portal.noDescription": "説明はまだありません。",
  "portal.reloaded": "最新の内容を読み込みました。",
  "portal.reload": "最新の内容を読み直す",
  "editor.title": "項目を編集",
  "editor.description": "記録する項目を追加し、使いやすい順に並べてください。",
  "editor.draftNotice":
    "下書きを保存した後に「変更を反映」を押すと、利用中のアプリに変更が適用されます。",
  "editor.appName": "アプリ名",
  "editor.descriptionLabel": "説明",
  "editor.icon": "アイコン",
  "editor.iconTree": "木",
  "editor.iconBook": "ノート",
  "editor.iconHome": "家",
  "editor.theme": "テーマ",
  "editor.themeForest": "深緑",
  "editor.themeLeaf": "葉",
  "editor.themeMoss": "苔",
  "editor.fields": "項目の設定",
  "editor.newApp": "新しいアプリ",
  "editor.newField": "新しい項目",
  "editor.addField": "項目を追加",
  "editor.empty": "項目はまだありません。「項目を追加」から始めてください。",
  "editor.unnamedField": "名前のない項目",
  "editor.reorder": "⠿ 並べ替え",
  "editor.optionOne": "選択肢1",
  "editor.optionTwo": "選択肢2",
  "editor.optionsHint": "一行に一つずつ入力してください。",
  "editor.unique": "値の重複を禁止する",
  "editor.formulaHint":
    "数値項目と + − * /、括弧を使って式を入力します。参照する項目が未入力なら、計算結果も空になります。",
  "editor.deleteField": "項目を削除",
  "editor.saveDraft": "下書きを保存",
  "editor.create": "アプリを作成",
  "editor.preview": "動作確認",
  "editor.publish": "変更を反映",
  "editor.previewTitle": "下書きの動作確認",
  "editor.notSaved": "保存されません",
  "editor.published": "変更を反映しました。",
  "editor.draftSaved": "下書きを保存しました。",
  "records.duplicateApp": "アプリを複製",
  "records.draftTitle": "このアプリは下書きです",
  "records.draftDescription":
    "項目の動作を確認して「変更を反映」を押すと、記録を追加できます。",
  "records.openDraft": "下書きを開く",
  "records.title": "記録",
  "records.add": "記録を追加",
  "records.empty": "記録はまだありません。「記録を追加」から始めてください。",
  "records.table": "記録一覧",
  "records.selection": "選択",
  "records.number": "番号",
  "records.actions": "操作",
  "records.deleteWarning": "削除した記録は元に戻せません。",
  "records.confirmDelete": "削除を確定",
  "records.edit": "記録の編集",
  "records.new": "新しい記録",
  "records.createdBy": "作成者",
  "records.updatedBy": "更新者",
  "records.createdAt": "作成日時",
  "records.updatedAt": "更新日時",
  "records.saved": "記録を保存しました。",
  "records.deleted": "記録を削除しました。",
  "records.save": "記録を保存",
  "records.check": "入力を確認",
  "records.checked":
    "入力を確認しました。この動作確認では記録は保存されません。",
  "records.noFields": "項目がまだありません。「項目を編集」から追加できます。",
  "records.noCandidates":
    "候補がありません。項目編集画面で候補を登録してください。",
  "announcements.title": "お知らせ",
  "announcements.add": "お知らせを追加",
  "announcements.reload": "お知らせを読み直す",
  "announcements.loading": "お知らせを読み込んでいます…",
  "announcements.empty": "お知らせはまだありません。",
  "announcements.edit": "お知らせの編集",
  "announcements.saved": "お知らせを保存しました。",
  "announcements.titleLabel": "お知らせのタイトル",
  "announcements.bodyLabel": "お知らせの本文",
  "announcements.save": "お知らせを保存",
  "announcements.deleted": "お知らせを削除しました。",
  "announcements.confirmDelete": "お知らせの削除を確定",
  "directory.title": "ユーザー・組織・グループの候補",
  "directory.description":
    "このアプリで選ぶ候補を登録します。IDは半角英字で始めてください。英数字とハイフン、下線を使えます。",
  "directory.empty": "候補はまだありません。",
  "directory.delete": "候補を削除",
  "workflow.settings": "状態と担当者の設定",
  "workflow.todo": "未着手",
  "workflow.enabled": "状態と担当者を使う",
  "workflow.assigneesHint":
    "担当候補は「ユーザー・組織・グループの候補」に登録したユーザーから選びます。",
  "workflow.initial": "初期状態",
  "workflow.noUsers": "ユーザー候補を登録すると選択できます。",
  "workflow.deleteState": "状態を削除",
  "workflow.newState": "新しい状態",
  "workflow.addState": "状態を追加",
  "workflow.transitions": "状態を変える操作",
  "workflow.deleteTransition": "操作を削除",
  "workflow.newTransition": "状態を変更",
  "workflow.addTransition": "遷移を追加",
  "workflow.title": "状態と担当者",
  "workflow.saveAssignee": "担当者を保存",
  "workflow.saved": "状態と担当者を保存しました。",
  "fieldTypes.text": "一行テキスト",
  "fieldTypes.textarea": "複数行テキスト",
  "fieldTypes.number": "数値",
  "fieldTypes.radio": "ラジオボタン",
  "fieldTypes.select": "ドロップダウン",
  "fieldTypes.checkbox": "チェックボックス",
  "fieldTypes.multiselect": "複数選択",
  "fieldTypes.date": "日付",
  "fieldTypes.time": "時刻",
  "fieldTypes.datetime": "日時",
  "fieldTypes.url": "URL",
  "fieldTypes.tel": "電話番号",
  "fieldTypes.email": "メールアドレス",
  "fieldTypes.calculation": "計算",
  "fieldTypes.user": "ユーザー",
  "fieldTypes.organization": "組織",
  "fieldTypes.group": "グループ",
  "templates.dailyName": "暮らしの記録",
  "templates.dailyDescription": "日々の用事や気づきをまとめます。",
  "templates.content": "内容",
  "templates.note": "メモ",
  "errors.loadAnnouncements": "お知らせを読み込めません。読み直してください。",
  "errors.operationFailed": "操作に失敗しました。再試行してください。",
  "errors.network":
    "接続できません。入力内容は残っています。もう一度お試しください。",
  "errors.unreadableResponse":
    "応答を読み取れません。接続先を確認してください。",
  "errors.failedResponse": "操作に失敗しました。接続先を確認してください。",
  "errors.invalidResponse":
    "応答の形式が一致しません。接続先を確認してください。",
  "errors.loadApps": "読み込みに失敗しました。再試行してください。",
  "errors.unexpected": "操作を完了できません。もう一度お試しください。",
  "errors.renderRoot": "画面の描画先が見つかりません。",
  "errors.appName": "アプリ名を入力してください。",
  "errors.duplicateFieldId": "項目IDが重複しています。",
  "errors.unsupportedUnique": "この種類には重複禁止を設定できません。",
  "errors.formulaReferences": "式には数値項目だけを参照してください。",
  "errors.formula": "式を確認してください。",
  "errors.options": "重複しない選択肢を入力してください。",
  "errors.candidateId": "候補IDを重複しない値にしてください。",
  "errors.states": "状態IDの重複と初期状態を確認してください。",
  "errors.assignees": "担当候補は登録済みのユーザーから選んでください。",
  "errors.transitions":
    "遷移IDの重複と遷移元・遷移先の状態を確認してください。",
  "errors.definition": "アプリ名と項目の設定を確認してください。",
  "errors.invalidValue": "項目の型に合う値を入力してください。",
  "errors.unknownField": "定義にない項目が含まれています。",
  "errors.calculation": "計算できません。",
  "errors.announcementTitle": "タイトルを入力してください。",
  "errors.announcementRevision": "更新にはIDとリビジョンが必要です。",
  "errors.announcementInput": "お知らせのタイトルと本文を確認してください。",
  "errors.announcementNotFound": "お知らせが見つかりません。",
  "errors.announcementConflict":
    "お知らせが変更されています。最新の内容を読み直してください。",
  "errors.announcementDeleteConflict":
    "お知らせが変更または削除されています。最新の内容を読み直してください。",
  "errors.appNotFound": "アプリが見つかりません。入口から選び直してください。",
  "errors.conflict":
    "別の操作で変更されています。最新の内容を読み直してください。",
  "errors.duplicates": "重複している項目を修正してください。",
  "errors.createConflict": "作成が競合しました。もう一度お試しください。",
  "errors.incompatibleRecords":
    "新しい項目に適合しない記録があります。記録または下書きを修正してください。",
  "errors.notPublished": "先にアプリの変更を反映してください。",
  "errors.input": "入力内容を確認してください。",
  "errors.recordNotFoundReload":
    "記録が見つかりません。最新の内容を読み直してください。",
  "errors.publishFirst": "先にアプリを反映してください。",
  "errors.recordNotFound": "記録が見つかりません。",
  "errors.deleteRecordNotFound":
    "削除対象の記録が見つかりません。最新の内容を読み直してください。",
  "errors.workflowMissing": "この記録には状態が設定されていません。",
  "errors.transitionUnavailable": "現在の状態からはこの操作を実行できません。",
  "errors.assigneeUnavailable": "この状態の担当候補から選んでください。",
  "errors.origin": "許可されていない接続元です。",
  "errors.json": "JSON形式で送信してください。",
  "errors.request": "送信内容の形式を確認してください。",
  "errors.storage": "保存先に接続できません。時間をおいて再試行してください。",
  "errors.route": "操作先が見つかりません。",
  "errors.localOnly": "この基本版はローカル検証用です。",
  "calculation.parenthesis": "括弧を閉じてください。",
  "calculation.finite": "有限の数値を入力してください。",
  "calculation.syntax":
    "数値、数値項目、四則演算と括弧で式を入力してください。",
  "calculation.characters": "式に使えない文字が含まれています。",
  "calculation.number": "参照する項目に数値を入力してください。",
  "calculation.zero": "0で割ることはできません。",
  "calculation.range": "計算結果が扱える数値の範囲を超えています。",
  "portal.appCount": "{{count}}件",
  "portal.recordCount": "{{count}}件の記録",
  "records.caption": "{{name}}の記録",
  "records.deleteSelected": "選んだ{{count}}件を削除",
  "records.deleteConfirm": "選んだ{{count}}件の記録を削除しますか？",
  "announcements.deleteConfirm": "「{{title}}」を削除しますか？",
  "editor.fieldsTitle": "{{name}}の項目",
  "editor.insert": "{{label}}を挿入",
  "workflow.current": "現在の状態：{{name}}",
  "workflow.stateAssignees": "{{name}}の担当候補",
  "app.documentTitle": "forma | 情報共有",
  "announcements.editNamed": "{{title}}を編集",
  "announcements.deleteNamed": "{{title}}を削除",
  "editor.copyName": "{{name}}のコピー",
  "records.selectNamed": "記録{{number}}を選択",
  "records.openNamed": "記録{{number}}を開く",
  "records.reuseNamed": "記録{{number}}を再利用",
  "records.details": "記録{{number}}の詳細・編集",
  "editor.drag": "{{label}}をドラッグ",
  "editor.uniqueNamed": "{{label}}の重複を禁止する",
  "editor.upNamed": "{{label}}を上へ",
  "editor.downNamed": "{{label}}を下へ",
  "editor.deleteNamed": "{{label}}の項目を削除",
  "editor.fieldName": "項目{{position}}の名前",
  "editor.fieldType": "項目{{position}}の種類",
  "editor.fieldOptions": "項目{{position}}の選択肢",
  "editor.fieldFormula": "項目{{position}}の計算式",
  "editor.insertNamed": "{{label}}の式に{{reference}}を挿入",
  "workflow.stateSettings": "状態{{position}}の設定",
  "workflow.stateName": "状態{{position}}の名前",
  "workflow.stateFallback": "状態{{position}}",
  "workflow.deleteStateNamed": "状態{{position}}を削除",
  "workflow.transitionName": "遷移{{position}}の操作名",
  "workflow.deleteTransitionNamed": "遷移{{position}}を削除",
  "workflow.transitionFrom": "遷移{{position}}の変更前",
  "workflow.transitionTo": "遷移{{position}}の変更後",
  "directory.users.settings": "ユーザーの候補設定",
  "directory.users.new": "新しいユーザー",
  "directory.users.add": "ユーザー候補を追加",
  "directory.users.id": "ユーザー{{position}}のID",
  "directory.users.name": "ユーザー{{position}}の名前",
  "directory.users.delete": "ユーザー{{position}}の候補を削除",
  "directory.organizations.settings": "組織の候補設定",
  "directory.organizations.new": "新しい組織",
  "directory.organizations.add": "組織候補を追加",
  "directory.organizations.id": "組織{{position}}のID",
  "directory.organizations.name": "組織{{position}}の名前",
  "directory.organizations.delete": "組織{{position}}の候補を削除",
  "directory.groups.settings": "グループの候補設定",
  "directory.groups.new": "新しいグループ",
  "directory.groups.add": "グループ候補を追加",
  "directory.groups.id": "グループ{{position}}のID",
  "directory.groups.name": "グループ{{position}}の名前",
  "directory.groups.delete": "グループ{{position}}の候補を削除",
  "errors.recordWorkflow":
    "記録{{number}}の状態または担当者が新しい設定に含まれていません。",
  "errors.duplicateValue":
    "{{label}}が記録{{previous}}と記録{{number}}で重複しています。",
  "errors.fieldDetail": "{{label}}: {{detail}}",
  "errors.recordDetail": "記録{{number}}: {{detail}}",
  "errors.identifier":
    "IDは半角英字で始めてください。英数字とハイフン、下線を使えます。",
  "errors.requiredName": "名前を入力してください。",
  "errors.fieldValue.text": "{{label}}には文字を入力してください。",
  "errors.fieldValue.textarea": "{{label}}には文字を入力してください。",
  "errors.fieldValue.number": "{{label}}には数値を入力してください。",
  "errors.fieldValue.radio": "{{label}}は選択肢から一つ選んでください。",
  "errors.fieldValue.select": "{{label}}は選択肢から一つ選んでください。",
  "errors.fieldValue.checkbox":
    "{{label}}は登録されている選択肢から重複せずに選んでください。",
  "errors.fieldValue.multiselect":
    "{{label}}は登録されている選択肢から重複せずに選んでください。",
  "errors.fieldValue.date": "{{label}}には有効な日付を入力してください。",
  "errors.fieldValue.time": "{{label}}には有効な時刻を入力してください。",
  "errors.fieldValue.datetime": "{{label}}には有効な日時を入力してください。",
  "errors.fieldValue.url":
    "{{label}}にはhttpまたはhttpsで始まるURLを入力してください。",
  "errors.fieldValue.tel": "{{label}}には電話番号を文字で入力してください。",
  "errors.fieldValue.email":
    "{{label}}には有効なメールアドレスを入力してください。",
  "errors.fieldValue.user":
    "{{label}}は登録されているユーザーから重複せずに選んでください。",
  "errors.fieldValue.organization":
    "{{label}}は登録されている組織から重複せずに選んでください。",
  "errors.fieldValue.group":
    "{{label}}は登録されているグループから重複せずに選んでください。",
} as const;
